In [21]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, RobustScaler
from category_encoders import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression 
from sklearn.model_selection import train_test_split

In [3]:
data= {
    'product_name': (np.nan,'sugar',np.nan,'milk',np.nan),
    'p_price_total($)': (np.nan,15,np.nan,8,8),
    'quantity':(10,np.nan,np.nan,10,20)
}

In [4]:
df= pd.DataFrame(data)
df

  product_name  p_price_total($)  quantity
0          NaN               NaN      10.0
1        sugar              15.0       NaN
2          NaN               NaN       NaN
3         milk               8.0      10.0
4          NaN               8.0      20.0

In [5]:
imputer= SimpleImputer(strategy='constant', fill_value=0)

In [6]:
imputer.fit_transform(df[['quantity','p_price_total($)']])

array([[10.,  0.],
       [ 0., 15.],
       [ 0.,  0.],
       [10.,  8.],
       [20.,  8.]])

In [7]:
imputer2= SimpleImputer(strategy='constant', fill_value='unknown')

In [8]:
imputer2.fit_transform(df[['product_name']])

array([['unknown'],
       ['sugar'],
       ['unknown'],
       ['milk'],
       ['unknown']], dtype=object)

In [9]:
imputer3= SimpleImputer(strategy='mean')
imputer3.fit_transform(df[['p_price_total($)','quantity']])

array([[10.33333333, 10.        ],
       [15.        , 13.33333333],
       [10.33333333, 13.33333333],
       [ 8.        , 10.        ],
       [ 8.        , 20.        ]])

In [10]:
imputer4= SimpleImputer(strategy='median')
imputer4.fit_transform(df[['p_price_total($)','quantity']])

array([[ 8., 10.],
       [15., 10.],
       [ 8., 10.],
       [ 8., 10.],
       [ 8., 20.]])

In [11]:
imputer5= SimpleImputer(strategy='most_frequent')
imputer5.fit_transform(df[['p_price_total($)','quantity']])

array([[ 8., 10.],
       [15., 10.],
       [ 8., 10.],
       [ 8., 10.],
       [ 8., 20.]])

In [12]:
imputer6= SimpleImputer(strategy='most_frequent')
imputer5.fit_transform(df)

array([['milk', 8.0, 10.0],
       ['sugar', 15.0, 10.0],
       ['milk', 8.0, 10.0],
       ['milk', 8.0, 10.0],
       ['milk', 8.0, 20.0]], dtype=object)

In [32]:
data2= {
    'emp_name': ('shubham','karan',np.nan,'aadi',np.nan),
    'dname':('clerk',np.nan,'accounts',np.nan,'clerk'),
    'comm':(1000,np.nan,np.nan,90000,200),
    'dno': (100,np.nan,20,20,np.nan),
    'sal': (10000,1500000,np.nan,8000,800000)
    
}

In [33]:
df1=pd.DataFrame(data2)
df1

  emp_name     dname     comm    dno        sal
0  shubham     clerk   1000.0  100.0    10000.0
1    karan       NaN      NaN    NaN  1500000.0
2      NaN  accounts      NaN   20.0        NaN
3     aadi       NaN  90000.0   20.0     8000.0
4      NaN     clerk    200.0    NaN   800000.0

In [34]:
imputer6= SimpleImputer(strategy='median')
imputer6.fit_transform(df1[['sal','comm','dno']])

array([[1.00e+04, 1.00e+03, 1.00e+02],
       [1.50e+06, 1.00e+03, 2.00e+01],
       [4.05e+05, 1.00e+03, 2.00e+01],
       [8.00e+03, 9.00e+04, 2.00e+01],
       [8.00e+05, 2.00e+02, 2.00e+01]])

In [35]:
numerical_cols = Pipeline(
    steps=[
        ('Imputer',SimpleImputer(strategy='median')),
        ('scaling',RobustScaler())
    ])

In [36]:
categorical_cols = Pipeline(
    steps=[
        ('Imputer',SimpleImputer(strategy='median')),
        ('scaling',OneHotEncoder(handle_unknown='ignore'))
    ])

In [37]:
preprocessing= ColumnTransformer(
    transformers=[
        ('numerical_pipeline',numerical_cols,['sal','comm','dno']),
        ('categorical_pipeline',categorical_cols,['emp_name','dname'])
    ]
)

In [38]:
main_pipeline=Pipeline(
    steps=[
        ('pre',preprocessing),
        ('model', LinearRegression())
    ]
)

In [40]:
X=df.drop(columns=['sal'])
Y=df['sal']

KeyError: "['sal'] not found in axis"

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,train_size=0.8,random_state=42)

NameError: name 'X' is not defined

In [28]:
main_pipeline.fit(xtrain,ytrain)

NameError: name 'xtrain' is not defined